# Generated by Django 5.1.5 on 2025-01-20 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MATH', 'MATHEMATICS'), ('SCIENCE', 'Science'), ('HUMANITIES', 'Humanities'), ('LANGUAGES', 'languages'), ('ART', 'art'), ('TECH', 'Technology')], max_length=10)),
                ('Question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
